"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "./components/HeaderMain";
import NavbarLeft from "./components/NavbarLeft";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  if (pathname === "/login")
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain />
        <main className="flex">
          <NavbarLeft />
          {children}
        </main>
      </body>
    </html>
  );
}
